name: Update badges

on:
  schedule:
    # Runs at 2pm
    - cron: "* * * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@2.4.0
        with:       
          CREDLY_USER: pedro-paiva.bab8654b # optional, but default will use the same from github
