name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pedropaiva1/pedropaiva1@main
        with:       
          CREDLY_USER: pedro-paiva.bab8654b # optional, but default will use the same from github
